version: '3.8'

networks:
  local_network:
    driver: bridge

volumes:
  mongo-data:

services:
  app:
    container_name: demo-mongodb-app
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
        MONGODB_USERNAME: root
        MONGODB_PASSWORD: password
        MONGODB_DATABASE: library

    volumes:
      - ../..:/workspaces:cached
    networks:
      - local_network
      
    command: sleep infinity

  mongodb:
    container_name: demo-mongodb-db
    image: mongo:3.6.23
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: library
    networks:
      - local_network